global:
  scrape_interval:     10s
  evaluation_interval: 10s

  # Attach these labels to any time series or alerts when communicating with
  # external systems (federation, remote storage, Alertmanager).
  external_labels:
      monitor: 'docker-host-alpha'

# Load and evaluate rules in this file every 'evaluation_interval' seconds.
rule_files:
  - "rules.yml"

# Alerting specifies settings related to the Alertmanager
alerting:
  alertmanagers:
  - scheme: http
    static_configs:
    - targets:
      - 'alertmanager:9093'

# A scrape configuration containing exactly one endpoint to scrape.
scrape_configs:
  - job_name: 'pihole-exporter'
    scrape_interval: 5s
    static_configs:
      - targets: ['pihole-exporter:9617']

  - job_name: 'storb'
    scrape_interval: 5s
    static_configs:
      - targets: ['192.168.1.5:9100']

  - job_name: 'storb-cadvisor'
    scrape_interval: 5s
    static_configs:
      - targets: ['192.168.1.5:8080']

  - job_name: 'raspberry'
    scrape_interval: 5s
    static_configs:
      - targets: ['node-exporter:9100']

  - job_name: 'raspberry-cadvisor'
    scrape_interval: 5s
    static_configs:
      - targets: ['cadvisor:8080']

  - job_name: 'prometheus'
    scrape_interval: 5s
    static_configs:
      - targets: ['localhost:9090']

  - job_name: 'cloudflared'
    scrape_interval: 5s
    static_configs:
      - targets: ['192.168.1.4:49312']

  - job_name: 'unifi-poller'
    scrape_interval: 10s
    static_configs:
      - targets: ['unifi-poller:9130']

  - job_name: 'rpi_exporter'
    scrape_interval: 10s
    static_configs:
      - targets: ['rpi_exporter:9243']

  # - job_name: 'blackbox'
  #   scrape_interval: 10m
  #   scrape_timeout: 10s
  #   metrics_path: /probe
  #   params:
  #     module: [http_2xx]  # Look for a HTTP 200 response.
  #   static_configs:
  #     - targets:
  #         - http://prometheus.io    # Target to probe with http.
  #         - https://prometheus.io   # Target to probe with https.
  #         - https://www.youtube.com
  #   relabel_configs:
  #     - source_labels: [__address__]
  #       target_label: __param_target
  #     - source_labels: [__param_target]
  #       target_label: instance
  #     - target_label: __address__
  #       replacement: blackbox-exporter:9115  # The blackbox exporter's real hostname:port.
  #
  # - job_name: 'blackbox_ping'
  #   scrape_interval: 10m
  #   scrape_timeout: 10s
  #   metrics_path: /probe
  #   params:
  #     module: [icmp]
  #   static_configs:
  #     - targets:
  #         - www.google.com
  #         - 1.1.1.1
  #   relabel_configs:
  #     - source_labels: [__address__]
  #       target_label: __param_target
  #     - source_labels: [__param_target]
  #       target_label: instance
  #     - target_label: __address__
  #       replacement: blackbox-exporter:9115  # The blackbox exporter's real hostname:port.
