{
 "title": "Docker Host",
 "description": "Docker host metrics",
 "tags": [ "system" ],
 "time": { "from": "now-15m", "to": "now" },
 "refresh": "10s",
 "templating": {
  "list": [
   {
    "name": "node",
    "query": "label_values(node_filesystem_size_bytes, job)"
   }
  ]
 },
 "panels": [
  {
   "title": "Uptime",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 4, "x": 0, "y": 0 },
   "format": "s",
   "valueName": "avg",
   "targets": [
    {
     "expr": "node_time_seconds{job=~'$node'} - node_boot_time_seconds{job=~'$node'}"
    }
   ]
  },
  {
   "title": "CPU Idle",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 4, "x": 4, "y": 0 },
   "format": "percent",
   "valueName": "avg",
   "targets": [
    {
     "expr": "sum(rate(node_cpu_seconds_total{mode=\"idle\",job=~'$node'}[1m])) * 100 / scalar(count(node_cpu_seconds_total{mode=\"user\",job=~'$node'}))"
    }
   ]
  },
  {
   "title": "CPU Cores",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 4, "x": 8, "y": 0 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "expr": "count without(cpu, mode) (node_cpu_seconds_total{mode=\"idle\",job=~'$node'})"
    }
   ]
  },
  {
   "title": "Available Memory",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 4, "x": 12, "y": 0 },
   "format": "bytes",
   "valueName": "avg",
   "targets": [
    {
     "expr": "node_memory_MemAvailable_bytes{job=~'$node'}"
    }
   ]
  },
  {
   "title": "Free Swap",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 4, "x": 16, "y": 0 },
   "format": "bytes",
   "valueName": "avg",
   "targets": [
    {
     "expr": "node_memory_SwapFree_bytes{job=~'$node'}"
    }
   ]
  },
  {
   "title": "Free Storage",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 4, "x": 20, "y": 0 },
   "format": "bytes",
   "valueName": "avg",
   "targets": [
    {
     "expr": "sum(node_filesystem_free_bytes{fstype=\"ext4\",job=~'$node'})"
    }
   ]
  },
  {
   "title": "Load Average 1m",
   "type": "graph",
   "gridPos": { "h": 4, "w": 8, "x": 0, "y": 3 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "expr": "node_load1{job=~'$node'}", "legendFormat": "load 1m" }
   ]
  },
  {
   "title": "Processes",
   "type": "graph",
   "gridPos": { "h": 4, "w": 8, "x": 8, "y": 3 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "node_procs_running{job=~'$node'}",
     "legendFormat": "running"
    },
    {
     "expr": "node_procs_blocked{job=~'$node'}",
     "legendFormat": "blocked by I/O"
    }
   ]
  },
  {
   "title": "Interrupts",
   "type": "graph",
   "gridPos": { "h": 4, "w": 8, "x": 16, "y": 3 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": " irate(node_intr_total{job=~'$node'}[5m])",
     "legendFormat": "interrupts"
    }
   ]
  },
  {
   "title": "CPU Usage",
   "type": "graph",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 7 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "expr": "sum(rate(node_cpu_seconds_total{job=~'$node'}[1m])) by (mode) * 100 / scalar(count(node_cpu_seconds_total{mode=\"user\",job=~'$node'}))",
     "legendFormat": "{{ mode }}"
    }
   ]
  },
  {
   "title": "Filesystem Usage",
   "type": "graph",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 14 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "sum(node_filesystem_free_bytes{fstype=\"ext4\",job=~'$node'})",
     "legendFormat": "Free"
    }
   ]
  },
  {
   "title": "Memory Usage",
   "type": "graph",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 22 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "node_memory_MemTotal_bytes{job=~'$node'} - (node_memory_MemFree_bytes{job=~'$node'} + node_memory_Buffers_bytes{job=~'$node'} + node_memory_Cached_bytes{job=~'$node'})",
     "legendFormat": "Used"
    },
    {
     "expr": "node_memory_MemFree_bytes{job=~'$node'}",
     "legendFormat": "Free"
    },
    {
     "expr": "node_memory_Buffers_bytes{job=~'$node'}",
     "legendFormat": "Buffers"
    },
    {
     "expr": "node_memory_Cached_bytes{job=~'$node'}",
     "legendFormat": "Cached"
    }
   ]
  },
  {
   "title": "I/O Usage",
   "type": "graph",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 29 },
   "yaxes": [
    { "format": "Bps" }
   ],
   "targets": [
    {
     "expr": "sum(irate(node_disk_read_bytes_total{job=~'$node'}[1m]))",
     "legendFormat": "read"
    },
    {
     "expr": "sum(irate(node_disk_written_bytes_total{job=~'$node'}[1m]))",
     "legendFormat": "written"
    },
    {
     "expr": "sum(irate(node_disk_io_time_seconds_total{job=~'$node'}[1m]))",
     "legendFormat": "io time"
    }
   ]
  },
  {
   "title": "Network Usage",
   "type": "graph",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 36 },
   "yaxes": [
    { "format": "Bps" }
   ],
   "targets": [
    {
     "expr": "irate(node_network_receive_bytes_total{device!=\"lo\",job=~'$node'}[1m])",
     "legendFormat": "In: {{ device }}"
    },
    {
     "expr": "irate(node_network_transmit_bytes_total{device!=\"lo\",job=~'$node'}[1m])",
     "legendFormat": "Out: {{ device }}"
    }
   ]
  },
  {
   "title": "Swap Usage",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 43 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "node_memory_SwapTotal_bytes{job=~'$node'} - node_memory_SwapFree_bytes{job=~'$node'}",
     "legendFormat": "Used"
    },
    {
     "expr": "node_memory_SwapFree_bytes{job=~'$node'}",
     "legendFormat": "Free"
    }
   ]
  },
  {
   "title": "Swap I/O",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 43 },
   "yaxes": [
    { "format": "Bps" }
   ],
   "targets": [
    {
     "expr": "rate(node_vmstat_pswpin{job=~'$node'}[1m]) * 4096 or irate(node_vmstat_pswpin{job=~'$node'}[5m]) * 4096",
     "legendFormat": "In"
    },
    {
     "expr": "rate(node_vmstat_pswpout{job=~'$node'}[1m]) * 4096 or irate(node_vmstat_pswpout{job=~'$node'}[5m]) * 4096",
     "legendFormat": "Out"
    }
   ]
  }
 ]
}